### ISSUE TITLE
It looks three bmfont-text is not support chinese/japanese text

### ISSUE THREAD

**Issue by terryleee** [Jam3/three-bmfont-text#11]
how can i make it display other languages?

**Comment by mattdesl** [comment]
This only supports simple text layout, ie Latin languages with left-to-right text.

Something like Chinese or Arabic is unfortunately much more challenging, and outside of the scope of this module.

Instead you would have better luck rendering to a canvas element and turning it into WebGL textures.

Cheers! 😁
