### ISSUE TITLE
Non-ascii text handling

### ISSUE THREAD

**Issue by JoeGermuska** [Jam3/three-bmfont-text#16]
I'm a bit of a newb here, so my apologies if I'm missing something. It seems that this library doesn't correctly handle non-ascii text.

I checked out the repo and changed the text in `test-3d.js` to use both a literal `ñ` and the unicode escape `\u00f1` and in both cases, those characters simply don't appear.  I also used the unicode escape `\u0065` (e) and that was correctly rendered.

**Comment by mattdesl** [comment]
This library uses "bitmap fonts" which is a way of storing glyphs in a texture atlas like this:

![lato](https://cloud.githubusercontent.com/assets/1383811/23037369/186de48c-f454-11e6-82f9-d50d61631953.png)

So you are limited by which glyphs you select for your texture atlas. When exporting with Hiero or a [similar tool](https://github.com/mattdesl/text-modules#bitmap-text), you should be able to add characters like `'ñ'` to the glyph atlas.

Other features like ligatures, right-to-left text and certain oriental languages are much more difficult to achieve and out of scope of this library. :smile:

**Comment by JoeGermuska** [comment]
I see. Thank you for the clarification. I was able to use Hiero to make a texture atlas with some of the characters I need.
