### ISSUE TITLE
Feature: API to expose shaders

### ISSUE THREAD

**Issue by patricknelson** [Jam3/three-bmfont-text#20]
Hi, thanks for building this. I am currently referencing the shaders stored under this package like so:

```js
const createText = require('three-bmfont-text');
const SDFShader = require('three-bmfont-text/shaders/sdf');
```

But this seems potentially brittle, e.g. what if you decide you need to change the path? It's not as well encapsulated as it could be. Also, I could potentially copy the shader to my local repository, but what if there are some tight bindings between this library and the shader that could go out of sync? Instead, what if I could do this:

```js
const createText = require('three-bmfont-text'); // Returns TextGeometry (subclass of THREE.BufferGeometry)
const SDFShader = createText.shaders.SDF;

// ... or maybe...
const SDFShader = require('three-bmfont-shaders').SDF
```

What do you think?

**Comment by mattdesl** [comment]
Thanks!

The paths won't get changed, it is a design choice and part of the module. You can just require it and not worry about any issues, it's no more brittle than if it was included in the index.

I will probably leave it as it is now since it is a mostly aesthetic change.

**Comment by patricknelson** [comment]
Ok cool I'll stick with this then 👍  not a huge deal, thanks!
